### ISSUE TITLE
HyperparamOpt is an abstract superclass and cannot be directly instantiated error

### ISSUE THREAD

**Issue by gokhantahil** [PacktPublishing/B11179_Hands-On-GPU-Computing-with-Python-#2]
Hello, 

I try to optimize the hyperparameters, 11 months ago (deepchem = 2.2) I was able to use it but now it doesn't work. 

`def rf_model_builder(model_params, model_dir):`
`  sklearn_model = RandomForestRegressor(**model_params)`
`  return dc.models.SklearnModel(sklearn_model, model_dir)`
`params_dict = {`
`    "n_estimators": [10, 100],`
`    "max_features": ["auto", "sqrt", "log2", None],`
`}`

`metric = dc.metrics.Metric(dc.metrics.r2_score)`
`optimizer = dc.hyper.HyperparamOpt(rf_model_builder)`
`best_rf, best_rf_hyperparams, all_rf_results = optimizer.hyperparam_search(`
`    params_dict, train_dataset, valid_dataset, transformers,`
`    metric=metric)`

> File "dc.py", line 107, in <module>
>     optimizer = dc.hyper.HyperparamOpt(rf_model_builder)
>   File "/home/kuruntu/anaconda3/lib/python3.8/site-packages/deepchem/hyper/base_classes.py", line 72, in __init__
>     raise ValueError(
> ValueError: HyperparamOpt is an abstract superclass and cannot be directly instantiated.           You probably want to instantiate a concrete subclass instead.

Could you please help me?
Thanks

**Comment by avimanyu786** [comment]
Hi @gokhantahil!

Thanks for reading my book and using [DeepChem](https://deepchem.io)! Your query has been reported earlier on the official repository as https://github.com/deepchem/deepchem/issues/2122 issue. Please try the workaround provided there. It's still in open status. In case the workaround doesn't work, you can directly comment on the issue. It'll be great if you also keep us posted here, about how it went. All the best!
